version: '3'

services:
  deep-leaning-ffws:
    image: ffws_python
    container_name: ffws-deep-learning
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3